# Week#02: Python Libraries (Part I)
**Course:** WMASDS04-Introduction to Data Science with Python
<br>**Instructor:** Farhana Afrin Duti, Department of Statistics, JU

<br>**Objectives:** 
- Numpy
- Pandas
- Matplotlib
- Seaborn

#### Ndarray
- Random Number Generation
- Vector representation of data
- Matrix representation of data
- Statistical Function
- Slicing

#### DataFrame
- Creating dataframe from list, dictionary
- Extracting subset of dataframe
- Adding row or column
- Dropping row or column
- Sorting data
- Grouping data

### Numpy Library
Numpy stands for Numerical Python

- Importing Numpy

In [1]:
# Import numpy
import numpy as np 
ar1 = np.array([1,2,3])
print(ar1)
print(type(ar1))

[1 2 3]
<class 'numpy.ndarray'>


- Generating Random Numbers in Numpy

In [2]:
 #set the seed and generate 7 random numbers between 1 and 50
np.random.seed(3)            
rn = np.random.randint(0,50,7)
print(rn)
print(type(rn))

[42 24  3  8  0 21 19]
<class 'numpy.ndarray'>


- Vector Creation

In [3]:
v1 = np.array([1,2,3,4,5,6])         #verctor in a row
print(v1)

v2 = np.array([[1],[2],[3],[4],[5],[6]])    #vector as a column
print(v2)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


- Extracting elements from vector

In [4]:
v1[2]

3

In [5]:
v1[2:4]

array([3, 4])

In [6]:
print(v1[:3])
print(v1[3:])
print(v1[-1])

[1 2 3]
[4 5 6]
6


In [7]:
v2[1:5]

array([[2],
       [3],
       [4],
       [5]])

- **Matrix in Numpy**

In [8]:
m1= np.array([[1,2,3],[4,5,6]])
print(m1)

[[1 2 3]
 [4 5 6]]


In [9]:
m1.ndim         #dimension of matrix
m1.shape        # number of rows/columns
m1.dtype        # provide the data type of a matrix
m1.size         # number of elements
m1.reshape(3,2) #reshape the matrix based on given dimension
m1.T            #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
print('matrix dimension: ',m1.ndim)
print('shape of the matrix: ',m1.shape)
print('data type of matrix: ', m1.dtype)

matrix dimension:  2
shape of the matrix:  (2, 3)
data type of matrix:  int32


- **Statistical Functions**

In [11]:
np.max(m1)                     #print maximum value of a matrix
np.min(m1)                     #print minimu 
np.max(m1,axis = 0)            #Print the maximum value for each column, set axis = 0
np.min(m1,axis = 0)            #Print the maximum value for each column
np.max(m1,axis = 1)            #Print the maximum value for each row
np.min(m1,axis = 1)            #Print the maximum value for each row, set axis = 1
np.mean(m1)
np.var(m1)
np.std(m1)
np.sqrt(m1)                    # print square root of all values of a matrix

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

- **slicing operations**

In [12]:
m1[0,2]                     #extracts the element in the first row and third column
m1[0,:]
m1[:,1]

array([2, 5])

## Pandas Library
Python library for data analysis


In [13]:
import pandas as pd

In [1]:
pd.Series()

NameError: name 'pd' is not defined

### DataFrame in Pandas

- A dataframe is a two dimensional, heterogenous tabular data structure in Pandas. 
- Each column has varied data types
- The dataframe object has two axex: axis 0 [rows] and axis 1 [columns]
- Both axes are labeled
- If the index is not mentioned explicitly, it is set automatically starting from 0.

### Creating DataFrame from List

In [15]:
import pandas as pd
# list of strings
list_str = ['John', 'Henry', 'Jack', 'Mary', 'Lucy','Angel', 'Santa']
# Creating dataframe from list
df_1 = pd.DataFrame(list_str)
# displaying dataframe
df_1

0
0   John
1  Henry
2   Jack
3   Mary
4   Lucy
5  Angel
6  Santa

***Assigning Row Index and Column Names***

In [16]:
df_1 = pd.DataFrame(list_str, index = ['a','b','c','d','e','f','g'], columns = ['Names'])
df_1

Names
a   John
b  Henry
c   Jack
d   Mary
e   Lucy
f  Angel
g  Santa

***Creating dataframe from multidimensional list***

In [17]:
list_multi = [['John',25],[ 'Henry',30], ['Jack',26], ['Mary',22]]
df_1 = pd.DataFrame(list_multi, index = ['a','b','c','d'], columns = ['Name', 'Age'])
df_1

Name  Age
a   John   25
b  Henry   30
c   Jack   26
d   Mary   22

### Creating DataFrame from Dictionary

In [1]:
data = {'Name':['John', 'Henry', 'Jack', 'Mary'],
        'Age': [27, 26, 24, 32],
        'Address':['NY','CA','TX','FL'],
        'Degree':['MS','MBA','BSc','Phd']}
df_2 = pd.DataFrame(data)

NameError: name 'pd' is not defined

In [19]:
df_2

Name  Age Address Degree
0   John   27      NY     MS
1  Henry   26      CA    MBA
2   Jack   24      TX    BSc
3   Mary   32      FL    Phd

In [6]:
#selecting two columns
df_2[['Name','Degree']
df_2

SyntaxError: '[' was never closed (942506923.py, line 2)

***Selecting column using index***

In [21]:
df_2[df_2.columns[1:4]]

Age Address Degree
0   27      NY     MS
1   26      CA    MBA
2   24      TX    BSc
3   32      FL    Phd

#### Extracting with .loc

In [2]:
#Creating lists of data
name = ['John', 'Henry', 'Jack', 'Mary']
age =  [27, 26, 24, 32]
address = ['NY','CA','TX','FL']
marks = [90,40,80,98]
Qualification = ['MS','MBA','BSc','Phd']
#Creating dictionary from lists
data_dict = {'Name':name, 'Age':age, 'Address':address,'Marks':marks, 'Degree':Qualification}
data_dict

#Creating dataframe from dictionary
df_2 = pd.DataFrame(data_dict,index = ['ID01','ID02','ID03', 'ID04'])
df_2

NameError: name 'pd' is not defined

In [3]:
df_2.loc['ID01':'ID02','Name':'Marks']

NameError: name 'df_2' is not defined

In [24]:
df_2.loc['ID03',:]

Name       Jack
Age          24
Address      TX
Marks        80
Degree      BSc
Name: ID03, dtype: object

***Extracting using .iloc***

In [25]:
df_2.iloc[0:2,:]

Name  Age Address  Marks Degree
ID01   John   27      NY     90     MS
ID02  Henry   26      CA     40    MBA

In [26]:
df_2.iloc[0:2,1:3]

Age Address
ID01   27      NY
ID02   26      CA

***Adding Column to DataFrame***

In [27]:
df_2=pd.DataFrame(data_dict)
df_2

Name  Age Address  Marks Degree
0   John   27      NY     90     MS
1  Henry   26      CA     40    MBA
2   Jack   24      TX     80    BSc
3   Mary   32      FL     98    Phd

In [28]:
height = [5.1,6.2,5.1,5.2]
df_2['Height'] = height
df_2

Name  Age Address  Marks Degree  Height
0   John   27      NY     90     MS     5.1
1  Henry   26      CA     40    MBA     6.2
2   Jack   24      TX     80    BSc     5.1
3   Mary   32      FL     98    Phd     5.2

***Adding columns using assign()***

In [29]:
df_2 = pd.DataFrame(data_dict)
df_2

Name  Age Address  Marks Degree
0   John   27      NY     90     MS
1  Henry   26      CA     40    MBA
2   Jack   24      TX     80    BSc
3   Mary   32      FL     98    Phd

In [30]:
df_2 = df_2.assign(Height = [5.1,6.2,5.1,5.2])
df_2

Name  Age Address  Marks Degree  Height
0   John   27      NY     90     MS     5.1
1  Henry   26      CA     40    MBA     6.2
2   Jack   24      TX     80    BSc     5.1
3   Mary   32      FL     98    Phd     5.2

***Adding column using insert()***

In [31]:
df_2 = pd.DataFrame(data_dict)
df_2

Name  Age Address  Marks Degree
0   John   27      NY     90     MS
1  Henry   26      CA     40    MBA
2   Jack   24      TX     80    BSc
3   Mary   32      FL     98    Phd

In [32]:
df_2.insert(2,'Height',[5.1,6.2,5.1,5.2], allow_duplicates = True)
df_2

Name  Age  Height Address  Marks Degree
0   John   27     5.1      NY     90     MS
1  Henry   26     6.2      CA     40    MBA
2   Jack   24     5.1      TX     80    BSc
3   Mary   32     5.2      FL     98    Phd

***Adding row using append()***

In [33]:
df_3 = pd.DataFrame(data_dict)
df_3

Name  Age Address  Marks Degree
0   John   27      NY     90     MS
1  Henry   26      CA     40    MBA
2   Jack   24      TX     80    BSc
3   Mary   32      FL     98    Phd

In [34]:
new_row = {'Name':'Tom', 'Age': 35, 'Address':'WA', 'Marks': 70, 'Degree':'BA'}
# new_row = pd.DataFrame(data = ['Tom',35,'WA',70, 'BA'], columns = ['Name','Age','Address','Marks','Degree'])
new_row
# df_3 = df_3.append(new_row, ignore_index = True)
# df_3

{'Name': 'Tom', 'Age': 35, 'Address': 'WA', 'Marks': 70, 'Degree': 'BA'}

***Adding rows using concate()***

In [35]:
df_3 = pd.DataFrame(data_dict)
new_rows = {'Name':['Tom','Jack'], 'Age': [35, 32], 'Address':['WA','CA'], 'Marks': [70,75], 'Degree':['BA','BSc']}
new_rows=pd.DataFrame(new_rows)

In [36]:
# Concate by rows
df_4 = pd.concat([df_3,new_rows],axis = 0)
df_4

Name  Age Address  Marks Degree
0   John   27      NY     90     MS
1  Henry   26      CA     40    MBA
2   Jack   24      TX     80    BSc
3   Mary   32      FL     98    Phd
0    Tom   35      WA     70     BA
1   Jack   32      CA     75    BSc

In [37]:
# Concate by columns
df_4 = pd.concat([df_3,new_rows],axis = 1)
df_4

Name  Age Address  Marks Degree  Name   Age Address  Marks Degree
0   John   27      NY     90     MS   Tom  35.0      WA   70.0     BA
1  Henry   26      CA     40    MBA  Jack  32.0      CA   75.0    BSc
2   Jack   24      TX     80    BSc   NaN   NaN     NaN    NaN    NaN
3   Mary   32      FL     98    Phd   NaN   NaN     NaN    NaN    NaN

***Droping rows by index Label***

In [38]:
df_2 = pd.DataFrame(data_dict)
df_2
df_5 = df_2
df_5

Name  Age Address  Marks Degree
0   John   27      NY     90     MS
1  Henry   26      CA     40    MBA
2   Jack   24      TX     80    BSc
3   Mary   32      FL     98    Phd

In [39]:
df_5.set_index('Name', inplace = True)
df_5

Age Address  Marks Degree
Name                            
John    27      NY     90     MS
Henry   26      CA     40    MBA
Jack    24      TX     80    BSc
Mary    32      FL     98    Phd

In [40]:
df_5.drop(['John'], axis = 0, inplace = True)
df_5

Age Address  Marks Degree
Name                            
Henry   26      CA     40    MBA
Jack    24      TX     80    BSc
Mary    32      FL     98    Phd

***Dropping by column names***

In [41]:
df_5 = df_2

In [42]:
df_5.drop('Marks',axis = 1, inplace = True)
df_5

Age Address Degree
Name                     
Henry   26      CA    MBA
Jack    24      TX    BSc
Mary    32      FL    Phd

***Sorting the data frame***

In [43]:
df_5 = df_2

In [44]:
# Sorting by one column
df_5.sort_values('Age',axis = 0, inplace = True, ascending = True, na_position = 'last')
df_5

Age Address Degree
Name                     
Jack    24      TX    BSc
Henry   26      CA    MBA
Mary    32      FL    Phd

In [45]:
# Sorting by multiple columns
df_5.sort_values(['Age','Name'],axis = 0, inplace = True, ascending = True, na_position = 'last')
df_5

Age Address Degree
Name                     
Jack    24      TX    BSc
Henry   26      CA    MBA
Mary    32      FL    Phd

***Grouping the Data***

In [46]:
data = {'Name':['John', 'Henry', 'Jack', 'Mary', 'Martin', 'Joseph'],
        'Age': [27, 26, 24, 32, 25,34],
        'Salary':[10000,25000,15000,20000,10000,23000],
        'Address':['WA','CA','TX','FL', 'WA','CA'],
        'Degree':['MS','MBA','BSc','Phd','MSc', 'BSc']}
df_2 = pd.DataFrame(data)
df_2

Name  Age  Salary Address Degree
0    John   27   10000      WA     MS
1   Henry   26   25000      CA    MBA
2    Jack   24   15000      TX    BSc
3    Mary   32   20000      FL    Phd
4  Martin   25   10000      WA    MSc
5  Joseph   34   23000      CA    BSc

In [47]:
# Grouping by column
df_2.groupby('Address').mean()

Age   Salary
Address               
CA       30.0  24000.0
FL       32.0  20000.0
TX       24.0  15000.0
WA       26.0  10000.0

In [48]:
age_group = df_2['Age'].groupby(df_2['Degree'])
age_group.max()

Degree
BSc    34
MBA    26
MS     27
MSc    25
Phd    32
Name: Age, dtype: int64